config/routes.rb
Rails.application.routes.draw do



  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    '/signup',  to: 'users#new'
  get    '/about',   to: 'home#about'
  post 'messages/create', to: 'messages#create', as: 'create_message'
  resources :groups
  resources :members
  # resources :messages
  root 'home#index'
  get 'new_messages', to: 'messages#new_messages'
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :messages
  has_many :members
  has_many :users, through: :members

  validates :name, presence: true, uniqueness: true
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :group
  belongs_to :user

  validates :content, presence: true, length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :messages
  # has_many :groups, through: :messages

  has_many :members
  has_many :groups, through: :members

  validates :name, presence: true
  validates :nickname, presence: true, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  helper_method :logged_in_user, :correct_user, :admin_user

  private
   # Confirms a logged-in user.
  def logged_in_user
    unless logged_in?
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end

  # Confirms an admin user.
  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end

  def correct_user
    @user = User.find(params[:id])
    unless current_user?(@user)
      flash[:danger] = "You cannot perform this action."
      redirect_to(root_url)
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :correct_user, :users, only: [:new]
  before_action :get_group, only: [:show, :edit, :update]

  def new
    @group = Group.new
  end

  def create
    @group = Group.create(group_params)

    redirect_to user_path(current_user)
    
  end

  def show
    if has_access_to_group?
    else
      flash[:warning] = "You don't have access to the group."
      redirect_to user_path(current_user)
    end
  end

  def edit
    @users = User.all
  end

  def update
    if @group.update(member_params())
      flash[:success] = "Group updated successfully"
      redirect_to group_path(@group)
    else
      redirect_to edit_group_path(@group)
    end
    
  end
  
  private

  def get_group
    @group = Group.find(params[:id])
  end

  def group_params
    owner_id = current_user.id
    params[:group][:owner_id] = current_user.id.to_s
    params[:group][:user_ids] = params[:group][:user_ids].push(owner_id.to_s)
    params.require(:group).permit(:name,:owner_id, :user_ids => [])
  end

  def member_params
   member_param_arr = params.require(:group).permit(:name, user_ids: [])
   member_param_arr[:user_ids].shift
   member_param_arr
  end

  def users
    @users = User.all - [current_user]
  end

  def has_access_to_group?
    current_user.groups.include?(Group.find(params[:id]))
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  
  def about
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @message = Message.new(message_params)
    if @message.save
      
      redirect_to group_path(id: params[:message][:group_id])
    else
      flash[:mess_error] = "There was an error sending the message. Try again"
      redirect_to group_path(id: params[:message][:group_id])
    end
  end

  def new_messages
    render json: Message.all
  end

  private

  def message_params
    params.require(:message).permit(:user_id, :group_id, :content)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(nickname: params[:session][:nickname])
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user_path(user)
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :get_user,         only: [:show, :edit, :update]
  before_action :logged_in_user,   only: [:edit, :update, :show, :index, :destroy]
  before_action :correct_user,     only: [:edit, :update, :show]
  before_action :admin_user,       only: :destroy

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  def create
    @user = User.new(user_params(:name, :nickname, :age, :email, :password, :password_confirmation))
    if @user.save
      Member.create(group_id:1, user_id:@user.id) # HARDCODED, CHANGE IF DB RESET
      log_in @user
      redirect_to user_path(@user)
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to new_user_path
    end
  end

  def edit
    
  end

  def update
    if @user.update(user_params(:name, :email, :password, :password_confirmation))
      flash[:success] = "Profile updated"
      redirect_to user_path(current_user)
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to edit_user_path(current_user)
    end
  end

  def show
    
  end

  private

  def get_user
    @user = User.find(params[:id])
  end

  def user_params(*args)
    params.require(:user).permit(*args)
  end

 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Returns true if the given user is the current user.
  def current_user?(user)
    user == current_user
  end

  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/edit.html.erb
<div class="edit">

  <h1><%= @group.name %></h1>

  <%= form_for @group do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <ul>
      <%= f.collection_check_boxes :user_ids, @users, :id, :name do |b| %>
        <li>
          <%= b.label  %>
          <%= b.check_box %>
        </li>
      <% end %>
    </ul>
    <%= f.submit %>
  <% end %>

</div>

app/views/groups/new.html.erb
<%= form_for(@group) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br>

  <ul>
    <%= f.collection_check_boxes :user_ids, @users, :id, :name do |b| %>
      <li>
        <%= b.label %>
        <%= b.check_box %>
      </li>
    <% end %>
  </ul>
  <%= f.submit %>
<% end %>

app/views/groups/show.html.erb
<% if flash[:mess_error] %>
  <h1> <%= flash[:mess_error] %> </h1>
<% end %>

<div id='username' style='display: none;'><%= current_user.nickname %></div>
<div id='groupname' style='display: none;'><%= @group.name %></div>

<div class="container-messages">

  <div class="sidebar">
    <% if flash[:success] %>
      <div class="alert alert-success" role="alert">
        <%= flash[:success] %>
      </div>
    <% end %>
    <h4> <%= @group.name %> </h4>
    <ul class="nav flex-column">
      <% @group.users.each do |u| %>
        <li>
          <%= u.name %>
        </li>
      <% end %>
    </ul>
  </div>

  <div class="send-group">

    <%= form_tag create_message_path  do %>
      <input type="hidden" name='message[group_id]' value="<%= @group.id %>">
      <input type="hidden" name='message[user_id]' value="<%= current_user.id %>">
      <textarea maxlength="300" class="form-control" name='message[content]' placeholder="Type your message here..." rows="3"></textarea>
      <button type="submit" class="btn btn-default">Send</button>
    <% end %>

    <div class="container-fluid message-box" id="real-time">
      <% @group.messages.reverse.each do |m| %>
          <% if m.user.id == current_user.id  %>
            <div class="message-right">
              <p class="user-name">
                <%= m.user.nickname %>
              </p>
              <p><%= m.content %></p>
            </div>
          <% else %>
            <div class="message-left">
              <p class="user-name">
                <%= m.user.nickname %>
              </p>
              <p><%= m.content %></p>
            </div>
          <% end %>
      <% end %>
    </div>

    <%= link_to("Edit Group", edit_group_path) if @group.owner_id == current_user.id %>
  </div>
</div>

app/views/home/about.html.erb
<div class="about-container">
  <div class="about">
    <h2>To start: either <%= link_to 'login', login_path %> or <%= link_to 'create', signup_path %> a new user</h2>
    <h2>Once your account is created you can access an open chat</h2>
    <h2>On your profile page you can 
      <ul style="font-size: 20px;">
        <li>Join a channel and chat</li>
        <li>Create a channel</li>
      </ul> 
    </h2>
    <h2>You can edit your profile from "Settings"</h2>
    <h2>Have Fun!</h2>
  </div>
</div>

app/views/home/index.html.erb
<div class="home-page-container">
  <div class="home-page">
    <h1 style="font-size: 60px;" onclick="popUp();">ShutApp</h1>
    <p style="font-size: 20px;"> <%= 'Please login or register to continue' if !session[:user_id] %> </p>
    <p style="font-size: 20px;"> <%= 'Welcome!' if session[:user_id] %> </p>
  </div>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container-nav-bar">
    <img src='<%= image_path('rails.png') %>' 
          class='logo-image'
      >
    <div class="nav-bar-menu">
      <nav>
        <ul class="nav navbar-nav navbar-right nav-bar-list">
          <li><%= link_to "Home", root_path %></li>
          
          <% if logged_in? %>
            <li><%= link_to "Users", users_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu" style="background-color: white;">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Log out", logout_path, method: :delete %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Log in", login_path %></li>
          <% end %>
          <li><%= link_to "About", about_path %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= action_cable_meta_tag %>


    <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    
  </head>

  <body>
    <%= render  "layouts/header" %>
<% if flash[:danger] %>
  <h1 class="alert-danger" ><%= flash[:danger] %></h1>
<% end %>

    <main class="page-content">
    <%= yield %>
    </main>
  </body>
</html>

app/views/users/edit.html.erb
<% errors = flash[:errors] %>
<% if errors %>
  <% errors.each do |err| %>
    <h1 class="error"><%= err %></h1>
  <% end %>
<% end %>


<%= form_for @user do |f| %>

  <%= f.label :name %><br>
  <%= f.text_field :name %><br>

  <%= f.label :email %><br>
  <%= f.email_field :email %><br>

  <%= f.label :password %><br>
  <%= f.password_field :password %><br>

  <%= f.label :password_confirmation %><br>
  <%= f.password_field :password_confirmation %><br>

  <%= f.submit "Update Profile", class: "btn btn-primary" %>

<% end %>

app/views/users/index.html.erb
<div class="users-list">
  <ul>
    <% @users.each do |user| %>

      <li>
        <%= user.nickname %>
         <% if current_user.admin? && !current_user?(user) %>
        | <%= link_to "delete", user, method: :delete, data: { confirm: "You sure?" } %>
      <% end %>
      </li>
    <% end %>
  </ul>
</div>

app/views/users/new.html.erb
<div class="login-form">
  <% errors = flash[:errors] %>
  <% if errors %>
    <% errors.each do |err| %>
      <h1 class="error"><%= err %></h1>
    <% end %>
  <% end %>
  <%= form_for @user do |f| %>

    <%= f.label :name %><br>
    <%= f.text_field :name %><br>

    <%= f.label :nickname %><br>
    <%= f.text_field :nickname %><br>

    <%= f.label :age %><br>
    <%= f.number_field :age %><br>

    <%= f.label :email %><br>
    <%= f.email_field :email %><br>

    <%= f.label :password %><br>
    <%= f.password_field :password %><br>

    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %><br>

    <%= f.submit %>

  <% end %>
</div>

app/views/users/show.html.erb
<% if flash[:success] %>
  <h1 class="alert-success" ><%= flash[:success] %></h1>
<% end %>

<% if flash[:warning] %>
  <h1 class="alert-warning" ><%= flash[:warning] %></h1>
<% end %>



<h1><%= @user.name %></h1>
<p><%= @user.nickname %></p>

<h4> <%= link_to "Create a group and start chatting!", new_group_path(id: @user.id) %></h4>

<div class="dropdown">
  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
    My Groups
    <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
    <% @user.groups.each do |g| %>
      <% next if g.name.downcase.include?('shutapp') %>
      <li> <%= link_to g.name, group_path(g) %> </li>
    <% end %>
    <li role="separator" class="divider"></li>
    <li> <%= link_to "ShutApp Open Group", '/groups/1' %> </li>  <%#HARDCODED OPEN CHAT, CHANGE WHEN NEW DB IS CREATED!!!%>
  </ul>
</div>